baseURL = "https://awalterschulze.github.io/blog/"
languageCode = "en-us"
title = "Adenoid Adventures"
theme = "beautifulhugo" 
publishDir = "docs"
googleAnalytics = "UA-106798280-1"
pygmentsCodefences = true
pygmentsStyle= "pastie"

[Params]
  subtitle = "Walter Schulze's blog about Programming"
  logo = "avatar.jpg"
  favicon = "favicon.ico"
  dateFormat = "2006 January 2"
  commit = false
  rss = true

[Author]
  name = "Walter Schulze"
  email = "awalterschulze@gmail.com"
  github = "awalterschulze"
  linkedin = "schulzewalter"
  twitter = "awalterschulze"
